"""empty message

Revision ID: de747cf1d983
Revises: 8cda4f2832cf
Create Date: 2023-07-16 01:15:14.831971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de747cf1d983'
down_revision = '8cda4f2832cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('mobile', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('mobile')
        batch_op.drop_column('coordinator')

    # ### end Alembic commands ###
